apiVersion: apps/v1
kind: Deployment
metadata:
  name: zurich-weather-app
  labels:
    app: zurich-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zurich-weather-app
  template:
    metadata:
      labels:
        app: zurich-weather-app
    spec:
      containers:
      - name: weather-app
        image: thineshvalaiganapthy/argo-cd-web-app:latest
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
